
export const COUNTRIES = [
{"name":"Alabama","country":"United States"},
{"name":"Alaska","country":"United States"},
{"name":"Arizona","country":"United States"},
{"name":"Arkansas","country":"United States"},
{"name":"California","country":"United States"},
{"name":"Colorado","country":"United States"},
{"name":"Connecticut","country":"United States"},
{"name":"District of Columbia","alt":["Washington DC","Washington D.C."],"country":"United States"},
{"name":"Delaware","country":"United States"},
{"name":"Florida","country":"United States"},
{"name":"Georgia","country":"United States"},
{"name":"Hawaii","country":"United States"},
{"name":"Idaho","country":"United States"},
{"name":"Illinois","country":"United States"},
{"name":"Indiana","country":"United States"},
{"name":"Iowa","country":"United States"},
{"name":"Kansas","country":"United States"},
{"name":"Kentucky","country":"United States"},
{"name":"Louisiana","country":"United States"},
{"name":"Maine","country":"United States"},
{"name":"Maryland","country":"United States"},
{"name":"Massachusetts","country":"United States"},
{"name":"Michigan","country":"United States"},
{"name":"Minnesota","country":"United States"},
{"name":"Mississippi","country":"United States"},
{"name":"Missouri","country":"United States"},
{"name":"Montana","country":"United States"},
{"name":"Nebraska","country":"United States"},
{"name":"Nevada","country":"United States"},
{"name":"New Hampshire","country":"United States"},
{"name":"New Jersey","country":"United States"},
{"name":"New Mexico","country":"United States"},
{"name":"New York","country":"United States"},
{"name":"North Carolina","country":"United States"},
{"name":"North Dakota","country":"United States"},
{"name":"Ohio","country":"United States"},
{"name":"Oklahoma","country":"United States"},
{"name":"Oregon","country":"United States"},
{"name":"Pennsylvania","country":"United States"},
{"name":"Rhode Island","country":"United States"},
{"name":"South Carolina","country":"United States"},
{"name":"South Dakota","country":"United States"},
{"name":"Tennessee","country":"United States"},
{"name":"Texas","country":"United States"},
{"name":"Utah","country":"United States"},
{"name":"Vermont","country":"United States"},
{"name":"Virginia","country":"United States"},
{"name":"Washington","country":"United States"},
{"name":"West Virginia","country":"United States"},
{"name":"Wisconsin","country":"United States"},
{"name":"Wyoming","country":"United States"},
{"name":"American Samoa","country":"United States"},
{"name":"Guam","country":"United States"},
{"name":"Northern Mariana Islands","country":"United States"},
{"name":"Puerto Rico","country":"United States"},
{"name":"United States Minor Outlying Islands","country":"United States"},
{"name":"Virgin Islands","country":"United States"},

{"name":"Alberta","country":"Canada"},
{"name":"British Columbia","country":"Canada"},
{"name":"Manitoba","country":"Canada"},
{"name":"New Brunswick","country":"Canada"},
{"name":"Newfoundland and Labrador","country":"Canada","alt":["Newfoundland","Labrador"]},
{"name":"Nova Scotia","country":"Canada"},
{"name":"Nunavut","country":"Canada"},
{"name":"Northwest Territories","country":"Canada"},
{"name":"Ontario","country":"Canada"},
{"name":"Prince Edward Island","country":"Canada"},
{"name":"Quebec","country":"Canada"},
{"name":"Saskatchewan","country":"Canada"},
{"name":"Yukon","country":"Canada"},

{"name":"Ashmore and Cartier Islands","country":"Australia"},
{"name":"Australian Antarctic Territory","country":"Australia"},
{"name":"Australian Capital Territory","country":"Australia"},
{"name":"Christmas Island","country":"Australia"},
{"name":"Cocos Islands","country":"Australia"},
{"name":"Coral Sea Islands","country":"Australia"},
{"name":"Heard Island and McDonald Islands","country":"Australia"},
{"name":"Jervis Bay Territory","country":"Australia"},
{"name":"New South Wales","country":"Australia"},
{"name":"Norfolk Island","country":"Australia"},

{"name":"Northern Territory","country":"Australia"},
{"name":"Queensland","country":"Australia"},
{"name":"South Australia","country":"Australia"},
{"name":"Tasmania","country":"Australia"},
{"name":"Victoria","country":"Australia"},
{"name":"Western Australia","country":"Australia"},

{"name":"Aguascalientes","country":"Mexico"},
{"name":"Baja California","country":"Mexico"},
{"name":"Baja California Sur","country":"Mexico"},
{"name":"Campeche","country":"Mexico"},
{"name":"Chiapas","country":"Mexico"},
{"name":"Chihuahua","country":"Mexico"},
{"name":"Coahuila","country":"Mexico"},
{"name":"Colima","country":"Mexico"},
{"name":"Federal District","country":"Mexico"},
{"name":"Durango","country":"Mexico"},
{"name":"Guanajuato","country":"Mexico"},
{"name":"Guerrero","country":"Mexico"},
{"name":"Hidalgo","country":"Mexico"},
{"name":"Jalisco","country":"Mexico"},
{"name":"Mexico","country":"Mexico"},
{"name":"Michoacán","country":"Mexico"},
{"name":"Morelos","country":"Mexico"},
{"name":"Nayarit","country":"Mexico"},
{"name":"Nuevo León","country":"Mexico"},
{"name":"Oaxaca","country":"Mexico"},
{"name":"Puebla","country":"Mexico"},
{"name":"Querétaro","country":"Mexico"},
{"name":"Quintana Roo","country":"Mexico"},
{"name":"San Luis Potosí","country":"Mexico"},
{"name":"Sinaloa","country":"Mexico"},
{"name":"Sonora","country":"Mexico"},
{"name":"Tabasco","country":"Mexico"},
{"name":"Tamaulipas","country":"Mexico"},
{"name":"Tlaxcala","country":"Mexico"},
{"name":"Veracruz","country":"Mexico"},
{"name":"Yucatán","country":"Mexico"},
{"name":"Zacatecas","short":"ZA","alt":["ZAC"],"country":"Mexico"},


{ "name": "Avon", "country": "Great Britain" },
{ "name": "Bedfordshire", "country": "Great Britain" },
{ "name": "Berkshire", "country": "Great Britain" },
{ "name": "Borders", "country": "Great Britain" },
{ "name": "Bristol", "country": "Great Britain" },
{ "name": "Buckinghamshire", "country": "Great Britain" },
{ "name": "Cambridgeshire", "country": "Great Britain" },
{ "name": "Channel Islands", "country": "Great Britain" },
{ "name": "Cheshire", "country": "Great Britain" },
{ "name": "Cleveland", "country": "Great Britain" },
{ "name": "Cornwall", "country": "Great Britain" },
{ "name": "Cumbria", "country": "Great Britain" },
{ "name": "Derbyshire", "country": "Great Britain" },
{ "name": "Devon", "country": "Great Britain" },
{ "name": "Dorset", "country": "Great Britain" },
{ "name": "Durham", "country": "Great Britain" },
{ "name": "East Riding of Yorkshire", "country": "Great Britain" },
{ "name": "East Sussex", "country": "Great Britain" },
{ "name": "Essex", "country": "Great Britain" },
{ "name": "Gloucestershire", "country": "Great Britain" },
{ "name": "Greater Manchester", "country": "Great Britain" },
{ "name": "Hampshire", "country": "Great Britain" },
{ "name": "Herefordshire", "country": "Great Britain" },
{ "name": "Hertfordshire", "country": "Great Britain" },
{ "name": "Humberside", "country": "Great Britain" },
{ "name": "Isle of Man", "country": "Great Britain" },
{ "name": "Isle of Wight", "country": "Great Britain" },
{ "name": "Isles of Scilly", "country": "Great Britain" },
{ "name": "Kent", "country": "Great Britain" },
{ "name": "Lancashire", "country": "Great Britain" },
{ "name": "Leicestershire", "country": "Great Britain" },
{ "name": "Lincolnshire", "country": "Great Britain" },
{ "name": "London", "country": "Great Britain" },
{ "name": "Merseyside", "country": "Great Britain" },
{ "name": "Middlesex", "country": "Great Britain" },
{ "name": "Norfolk", "country": "Great Britain" },
{ "name": "North Yorkshire", "country": "Great Britain" },
{ "name": "Northamptonshire", "country": "Great Britain" },
{ "name": "Northumberland", "country": "Great Britain" },
{ "name": "Nottinghamshire", "country": "Great Britain" },
{ "name": "Oxfordshire", "country": "Great Britain" },
{ "name": "Rutland", "country": "Great Britain" },
{ "name": "Shropshire", "country": "Great Britain" },
{ "name": "Somerset", "country": "Great Britain" },
{ "name": "South Yorkshire", "country": "Great Britain" },
{ "name": "Staffordshire", "country": "Great Britain" },
{ "name": "Suffolk", "country": "Great Britain" },
{ "name": "Surrey", "country": "Great Britain" },
{ "name": "Tyne and Wear", "country": "Great Britain" },
{ "name": "Warwickshire", "country": "Great Britain" },
{ "name": "West Midlands", "country": "Great Britain" },
{ "name": "West Sussex", "country": "Great Britain" },
{ "name": "West Yorkshire", "country": "Great Britain" },
{ "name": "Wiltshire", "country": "Great Britain" },
{ "name": "Worcestershire", "country": "Great Britain" },

{ "name": "Antrim", "country": "Great Britain" },
{ "name": "Down", "country": "Great Britain" },
{ "name": "Fermanagh", "country": "Great Britain" },
{ "name": "Londonderry", "country": "Great Britain" },
{ "name": "Tyrone", "country": "Great Britain" },

{ "name": "Aberdeen City", "country": "Great Britain" },
{ "name": "Aberdeenshire", "country": "Great Britain" },
{ "name": "Angus", "country": "Great Britain" },
{ "name": "Argyll and Bute", "country": "Great Britain" },
{ "name": "Armagh", "country": "Great Britain" },
{ "name": "Carmarthenshire", "country": "Great Britain" },
{ "name": "Clackmannan", "country": "Great Britain" },
{ "name": "Dumfries and Galloway", "country": "Great Britain" },
{ "name": "East Ayrshire", "country": "Great Britain" },
{ "name": "East Dunbartonshire", "country": "Great Britain" },
{ "name": "East Lothian", "country": "Great Britain" },
{ "name": "East Renfrewshire", "country": "Great Britain" },
{ "name": "Edinburgh City", "country": "Great Britain" },
{ "name": "Falkirk", "country": "Great Britain" },
{ "name": "Fife", "country": "Great Britain" },
{ "name": "Glasgow", "country": "Great Britain" },
{ "name": "Highland", "country": "Great Britain" },
{ "name": "Inverclyde", "country": "Great Britain" },
{ "name": "Midlothian", "country": "Great Britain" },
{ "name": "Moray", "country": "Great Britain" },
{ "name": "North Ayrshire", "country": "Great Britain" },
{ "name": "North Lanarkshire", "country": "Great Britain" },
{ "name": "Orkney", "country": "Great Britain" },
{ "name": "Perthshire and Kinross", "country": "Great Britain" },
{ "name": "Renfrewshire", "country": "Great Britain" },
{ "name": "Roxburghshire", "country": "Great Britain" },
{ "name": "Shetland", "country": "Great Britain" },
{ "name": "South Ayrshire", "country": "Great Britain" },
{ "name": "South Lanarkshire", "country": "Great Britain" },
{ "name": "Stirling", "country": "Great Britain" },
{ "name": "West Dunbartonshire", "country": "Great Britain" },
{ "name": "West Lothian", "country": "Great Britain" },
{ "name": "Western Isles", "country": "Great Britain" },

{ "name": "Blaenau Gwent", "country": "Great Britain" },
{ "name": "Bridgend", "country": "Great Britain" },
{ "name": "Caerphilly", "country": "Great Britain" },
{ "name": "Cardiff", "country": "Great Britain" },
{ "name": "Ceredigion", "country": "Great Britain" },
{ "name": "Conwy", "country": "Great Britain" },
{ "name": "Denbighshire", "country": "Great Britain" },
{ "name": "Flintshire", "country": "Great Britain" },
{ "name": "Gwynedd", "country": "Great Britain" },
{ "name": "Isle of Anglesey", "country": "Great Britain" },
{ "name": "Merthyr Tydfil", "country": "Great Britain" },
{ "name": "Monmouthshire", "country": "Great Britain" },
{ "name": "Neath Port Talbot", "country": "Great Britain" },
{ "name": "Newport", "country": "Great Britain" },
{ "name": "Pembrokeshire", "country": "Great Britain" },
{ "name": "Powys", "country": "Great Britain" },
{ "name": "Rhondda Cynon Taff", "country": "Great Britain" },
{ "name": "Swansea", "country": "Great Britain" },
{ "name": "The Vale of Glamorgan", "country": "Great Britain" },
{ "name": "Torfaen", "country": "Great Britain" },
{ "name": "Wrexham", "country": "Great Britain" },


{ "name": "Auckland", "country": "New Zealand" },
{ "name": "New Plymouth", "country": "New Zealand" },
{ "name": "Hawke's Bay", "country": "New Zealand" },
{ "name": "Wellington", "country": "New Zealand" },
{ "name": "Nelson", "country": "New Zealand" },
{ "name": "Marlborough", "country": "New Zealand" },
{ "name": "Westland", "country": "New Zealand" },
{ "name": "Canterbury", "country": "New Zealand" },
{ "name": "Otago", "country": "New Zealand" },
{ "name": "Southland", "country": "New Zealand" }
]